/* Generated by Yosys 0.39+165 (git sha1 22c5ab90d, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "top.v:1.1-17.10" *)
module adder(a, b, s, c);
  (* src = "top.v:7.8-7.9" *)
  input a;
  wire a;
  (* src = "top.v:8.8-8.9" *)
  input b;
  wire b;
  (* src = "top.v:10.13-10.14" *)
  output c;
  wire c;
  (* src = "top.v:9.13-9.14" *)
  output s;
  wire s;
  (* src = "top.v:12.10-12.11" *)
  wire [31:0] y;
  assign c = a & (* src = "top.v:15.7-15.12" *) b;
  assign s = a ^ (* src = "top.v:14.7-14.12" *) b;
  assign y = 32'd32;
endmodule

(* cells_not_processed =  1  *)
(* src = "top.v:18.1-43.10" *)
module top(CLK, LED1);
  (* src = "top.v:39.2-42.5" *)
  wire [31:0] _0_;
  (* src = "top.v:22.8-22.11" *)
  input CLK;
  wire CLK;
  (* src = "top.v:23.13-23.17" *)
  output LED1;
  reg LED1;
  (* src = "top.v:25.6-25.7" *)
  wire a;
  (* src = "top.v:26.6-26.7" *)
  wire b;
  (* src = "top.v:24.13-24.20" *)
  reg [31:0] r_count;
  assign _0_ = r_count + (* src = "top.v:40.14-40.25" *) 32'd1;
  (* src = "top.v:39.2-42.5" *)
  always @(posedge CLK)
    LED1 <= r_count[22];
  (* src = "top.v:39.2-42.5" *)
  always @(posedge CLK)
    r_count <= _0_;
  assign a = 1'h0;
  assign b = 1'h1;
endmodule
